language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

before_script:
  - ./.travis/compile.sh

script: make test

after_script:
  - ./.travis/show-error.sh
